base: 
  project: comment-toxicity-detection
  author: Karan Shingde
  random_state: 42
  
data_source:
  s3_source:
    train_data: data/raw/train.csv
    test_data: data/raw/test.csv

load_data:
  processed_train_data: data/processed/processed_train_data.csv
  processed_test_data: data/processed/processed_test_data.csv

split_data:
  train_path: data/processed/cleaned_data.csv
  test_path: data/processed/cleaned_data.csv
  test_size: 0.2
