# CI/CD PIPELINE SCRIPT FOR GITHUB ACTIONS

# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

# workflow name
name: comment-toxicity-detection

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

# Worflow jobs
jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      